---
collections:
  - name: https://github.com/RedHatSatellite/satellite-operations-collection.git
    type: git
    version: master

  - name: https://github.com/RedHatSatellite/satellite-ansible-collection.git
    type: git
    version: develop

  - name: community.general
